import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.102.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
function secretKey(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{return JSON.parse(m).default||""}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{
 const jwt=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!jwt)return json({error:"Sessão ausente."},401);const url=Deno.env.get("SUPABASE_URL")||"",sk=secretKey();const admin=createClient(url,sk,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:ue}=await admin.auth.getUser(jwt);if(ue||!user)return json({error:"Sessão inválida."},401);
 const b=await req.json(),action=String(b.action||"send"),conversationId=String(b.conversationId||"");if(!conversationId)return json({error:"Conversa obrigatória."},400);
 const {data:c2,error:c2e}=await admin.from("whatsapp_conversations").select("id,studio_id,contact_id,last_customer_message_at,whatsapp_contacts(wa_id,profile_name)").eq("id",conversationId).single();if(c2e)throw c2e;
 const {data:member}=await admin.from("studio_members").select("active").eq("studio_id",c2.studio_id).eq("user_id",user.id).eq("active",true).maybeSingle();const {data:pa}=await admin.from("platform_admins").select("user_id").eq("user_id",user.id).maybeSingle();if(!member&&!pa)return json({error:"Sem acesso à conversa."},403);
 const {data:gvData}=await admin.rpc("get_whatsapp_graph_version"); const graphVersion=String(gvData||"v23.0");
 const {data:conn,error:co}=await admin.from("whatsapp_connections").select("waba_id,phone_number_id,status").eq("studio_id",c2.studio_id).single();if(co||conn.status!=="connected")return json({error:"WhatsApp não conectado."},400);const {data:tok,error:te}=await admin.rpc("get_whatsapp_access_token",{p_studio_id:c2.studio_id});if(te||!tok)return json({error:"Token do WhatsApp não disponível."},500);
 if(action==="list_templates"){const r=await fetch(`https://graph.facebook.com/${graphVersion}/${conn.waba_id}/message_templates?limit=100&status=APPROVED`,{headers:{Authorization:`Bearer ${tok}`}});const d=await r.json();if(!r.ok)return json({error:d?.error?.message||"Falha ao listar templates."},400);return json({ok:true,templates:d.data||[]});}
 const wa=(c2 as any).whatsapp_contacts?.wa_id;if(!wa)return json({error:"Contato sem wa_id."},400);let payload:any={messaging_product:"whatsapp",to:wa};let bodyText="",msgType=String(b.type||"text");
 if(action==="mark_read"){if(!b.messageId)return json({ok:true});payload={messaging_product:"whatsapp",status:"read",message_id:String(b.messageId)};const r=await fetch(`https://graph.facebook.com/${graphVersion}/${conn.phone_number_id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});await r.text();await admin.from("whatsapp_conversations").update({unread_count:0}).eq("id",conversationId);return json({ok:true});}
 if(msgType==="template"){const name=String(b.templateName||"").trim(),language=String(b.language||"pt_BR");if(!name)return json({error:"Template obrigatório."},400);payload.type="template";payload.template={name,language:{code:language},components:Array.isArray(b.components)?b.components:[]};bodyText=`[template] ${name}`;}else{bodyText=String(b.text||"").trim();if(!bodyText)return json({error:"Mensagem vazia."},400);payload.type="text";payload.text={body:bodyText,preview_url:false};}
 const r=await fetch(`https://graph.facebook.com/${graphVersion}/${conn.phone_number_id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return json({error:d?.error?.message||"Falha ao enviar mensagem.",meta_error:d?.error},400);const mid=d.messages?.[0]?.id||null,at=new Date().toISOString();
 const {data:row,error:ie}=await admin.from("whatsapp_messages").insert({studio_id:c2.studio_id,conversation_id:conversationId,contact_id:c2.contact_id,provider_message_id:mid,direction:"outbound",message_type:msgType,body:bodyText,status:"sent",template_name:msgType==="template"?String(b.templateName):null,sent_by:user.id,raw:d,message_at:at}).select("*").single();if(ie)throw ie;await admin.from("whatsapp_conversations").update({last_message_at:at,last_message_preview:bodyText}).eq("id",conversationId);return json({ok:true,message:row,provider:d});
}catch(e){console.error("whatsapp-send",e);return json({error:e instanceof Error?e.message:"Falha no WhatsApp."},500)}});
