(function(){'use strict';
const ctx=window.INTORNA_CTX, db=window.IntornaCloud?.client;if(!ctx||!db)return;
const $=id=>document.getElementById(id), h=s=>esc(s??''), sid=ctx.studioId;
let refs=[],gallery=[],templates=[],costs=[],aiUsage={used:0,limit:0};
function inject(){
 const nav=document.querySelector('.nav'); const before=nav.querySelector('[data-page="assinatura"]');
 const buttons=[['gerador','🎨','Gerar Imagens'],['galeria','🖼️','Portal & Galeria'],['marketplace','🧩','Marketplace'],['oportunidades','🎯','Oportunidades'],['indicacoes','🤝','Indicações']];
 for(const [id,ico,label] of buttons){if(nav.querySelector(`[data-page="${id}"]`))continue;const b=document.createElement('button');b.dataset.page=id;b.innerHTML=`<span class="ico">${ico}</span><span class="label">${label}</span>`;b.onclick=()=>goPage(id);nav.insertBefore(b,before)}
 const c=document.querySelector('.container'); c.insertAdjacentHTML('beforeend',pages());
 const link=document.createElement('link');link.rel='stylesheet';link.href='styles-v6.css';document.head.appendChild(link);
 const direct=$('director')?.querySelector('.card.half:first-child');if(direct)direct.insertAdjacentHTML('beforeend','<div class="space"></div><button class="btn gold" id="v6PlanBtn">Montar sequência inteligente</button><div id="v6DirectorPlan" class="prompt" style="margin-top:12px;display:none"></div>');
 bind();populateOrders();const wl=ctx.studio.settings?.white_label||{};if($('wlName'))$('wlName').value=wl.name||ctx.studio.name;if($('wlColor'))$('wlColor').value=wl.color||'#7c3aed';try{const oldSave=save;save=function(){oldSave();populateOrders();renderOpportunities()}}catch(_){}loadAll();
}
function pages(){return `
<section class="page" id="gerador"><div class="v6-grid"><div class="v6-card"><h2>Gerar imagens no Intorná Pixels</h2><label>Pedido</label><select id="aiOrder"><option value="">Sem pedido</option></select><label>Prompt</label><textarea id="aiPrompt" rows="10" placeholder="Use o AI Director ou escreva o prompt aqui."></textarea><div class="form-grid"><div><label>Quantidade</label><input id="aiQty" type="number" min="1" max="4" value="1"></div><div><label>Formato</label><select id="aiSize"><option value="1024x1536">Vertical 2:3</option><option value="1024x1024">Quadrado</option><option value="1536x1024">Horizontal</option></select></div><div><label>Qualidade</label><select id="aiQuality"><option>low</option><option selected>medium</option><option>high</option></select></div><div><label>Destino</label><select id="aiKind"><option value="contracted">Foto contratada</option><option value="extra">Foto extra</option></select></div></div><label>Fotos de referência do cliente</label><input id="aiRefs" type="file" accept="image/jpeg,image/png,image/webp" multiple><div id="aiRefList" class="v6-ai-ref-list"></div><div class="row"><button class="btn ghost" id="aiUsePrompt">Usar prompt do AI Director</button><button class="btn primary" id="aiGenerate">Gerar agora</button></div><p class="v6-note">As referências são armazenadas de forma privada. Quando usadas, o backend acrescenta regras de preservação fiel da identidade.</p></div><div class="v6-card"><div class="row" style="justify-content:space-between"><div><h2>Resultado</h2><p class="muted" id="aiUsage">Uso de IA: carregando…</p></div></div><div id="aiResults" class="v6-result"><div class="empty">As imagens geradas aparecerão aqui.</div></div></div></div></section>
<section class="page" id="galeria"><div class="v6-grid"><div class="v6-card"><h2>Galeria e portal do cliente</h2><label>Pedido</label><select id="galOrder"></select><div class="row"><button class="btn primary" id="portalLinkBtn">Gerar / renovar link</button><button class="btn ghost" id="portalCopyBtn" disabled>Copiar link</button></div><div id="portalLinkBox" class="v6-code" style="margin-top:12px">Selecione um pedido.</div><hr><h3>Adicionar fotografia</h3><label>Prévia (com marca-d’água para extra)</label><input id="galPreview" type="file" accept="image/jpeg,image/png,image/webp"><label>Arquivo final sem marca (recomendado)</label><input id="galFinal" type="file" accept="image/jpeg,image/png,image/webp"><div class="form-grid"><div><label>Tipo</label><select id="galKind"><option value="contracted">Contratada</option><option value="extra">Extra</option></select></div><div><label>Preço da extra</label><input id="galPrice" type="number" min="0" step="0.01" value="4.90"></div></div><button class="btn gold" id="galUpload">Adicionar à galeria</button></div><div class="v6-card"><h2>Fotos publicadas</h2><div id="galItems" class="v6-gallery"><div class="empty">Selecione um pedido.</div></div></div><div class="v6-card"><h2>White Label</h2><p class="v6-note">Disponível no plano Studio. No portal do cliente, sua marca pode aparecer sem destaque para o Intorná Pixels.</p><label>Nome exibido</label><input id="wlName"><label>Cor principal</label><input id="wlColor" type="color" value="#7c3aed"><label>Logo</label><input id="wlLogo" type="file" accept="image/png,image/jpeg,image/webp"><button class="btn primary" id="wlSave">Salvar identidade</button></div><div class="v6-card"><h2>Referências recebidas</h2><div id="galRefs"><div class="empty">Nenhuma referência.</div></div></div></div></section>
<section class="page" id="marketplace"><div class="card"><h2>Marketplace de ensaios</h2><p class="muted">Modelos prontos que preenchem a direção do ensaio e a sequência de fotos.</p><div id="templateList" class="v6-market"></div></div></section>
<section class="page" id="oportunidades"><div class="v6-grid"><div class="v6-card full"><h2>Ranking de oportunidades</h2><p class="muted">Prioriza clientes com fotos extras, pagamentos pendentes, aniversários próximos e pós-venda.</p><div id="oppList"></div></div><div class="v6-card"><h2>Lucro por ensaio</h2><label>Pedido</label><select id="costOrder"></select><label>Categoria</label><select id="costCategory"><option value="ai">IA</option><option value="ads">Anúncios</option><option value="tools">Ferramentas</option><option value="commission">Comissão</option><option value="labor">Mão de obra</option><option value="other">Outros</option></select><label>Descrição</label><input id="costDesc"><label>Valor</label><input id="costValue" type="number" min="0" step="0.01"><button class="btn primary" id="costAdd">Adicionar custo</button></div><div class="v6-card"><h2>Resumo de lucratividade</h2><div id="profitBox"></div></div></div></section>
<section class="page" id="indicacoes"><div class="v6-grid"><div class="v6-card"><h2>Seu código de indicação</h2><p>Indique outro estúdio. Quando a primeira assinatura for confirmada, a indicação fica qualificada.</p><div class="v6-code" id="refCode">Carregando…</div><div class="space"></div><button class="btn gold" id="refCopy">Copiar convite</button></div><div class="v6-card"><h2>Indicações</h2><div id="refStats"></div></div></div></section>`}
function bind(){
 $('aiOrder').onchange=()=>loadReferences($('aiOrder').value);$('aiRefs').onchange=showLocalRefs;$('aiUsePrompt').onclick=()=>{$('aiPrompt').value=$('promptOut')?.textContent||''};$('aiGenerate').onclick=generateImage;
 $('galOrder').onchange=()=>loadGallery($('galOrder').value);$('portalLinkBtn').onclick=createPortal;$('portalCopyBtn').onclick=()=>navigator.clipboard.writeText($('portalLinkBox').textContent).then(()=>toast('Link copiado.'));$('galUpload').onclick=uploadGallery;$('wlSave').onclick=saveWhiteLabel;
 $('v6PlanBtn').onclick=directorPlan;$('costAdd').onclick=addCost;$('costOrder').onchange=renderProfit;$('refCopy').onclick=copyReferral;
}
function populateOrders(){const opts=state.orders.map(o=>{const c=getClient(o.clientId);return `<option value="${o.id}">${h(c?.name||'Cliente')} — ${h(o.type||o.packageId)}</option>`}).join('');['aiOrder','galOrder','costOrder'].forEach(id=>{const e=$(id);if(!e)return;e.innerHTML=(id==='aiOrder'?'<option value="">Sem pedido</option>':'')+opts});}
async function loadAll(){await Promise.allSettled([loadTemplates(),loadAIUsage(),loadCosts(),loadReferral()]);renderOpportunities();renderProfit();if($('galOrder').value)loadGallery($('galOrder').value)}
async function uploadFile(file,path){const {error}=await db.storage.from('intorna-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
async function loadReferences(orderId){refs=[];if(!orderId){$('aiRefList').innerHTML='';return}const {data}=await db.from('client_references').select('*').eq('order_id',orderId).order('created_at',{ascending:false});refs=(data||[]).map(x=>x.file_path);$('aiRefList').innerHTML=(data||[]).map(x=>`<span>📎 ${h(x.original_name||'referência')}</span>`).join('')||'<span>Nenhuma referência salva</span>'}
function showLocalRefs(){const fs=[...$('aiRefs').files];$('aiRefList').innerHTML=fs.map(f=>`<span>⬆ ${h(f.name)}</span>`).join('')+(refs.length?refs.map(()=>'<span>📎 referência salva</span>').join(''):'')}
async function generateImage(){const btn=$('aiGenerate'),orderId=$('aiOrder').value;try{btn.disabled=true;btn.textContent='Gerando…';let paths=[...refs];for(const f of [...$('aiRefs').files]){const p=`${sid}/${orderId||'general'}/references/${crypto.randomUUID()}-${f.name.replace(/[^a-z0-9._-]/gi,'_')}`;await uploadFile(f,p);paths.push(p);if(orderId)await db.from('client_references').insert({studio_id:sid,order_id:orderId,file_path:p,original_name:f.name,mime_type:f.type,source:'studio'})}const {data,error}=await db.functions.invoke('generate-image',{body:{studioId:sid,orderId:orderId||null,prompt:$('aiPrompt').value.trim(),quantity:Number($('aiQty').value),size:$('aiSize').value,quality:$('aiQuality').value,referencePaths:paths,addToGallery:!!orderId,kind:$('aiKind').value,price:Number(state.config.extraPhotoPrice||4.9)}});if(error)throw error;if(data?.error)throw new Error(data.error);$('aiResults').innerHTML=(data.images||[]).map((u,i)=>`<div><img src="${u}" alt="Imagem ${i+1}"><p><b>Imagem ${i+1}</b></p></div>`).join('')||'<div class="empty">Nenhuma imagem retornada.</div>';aiUsage=data.usage||aiUsage;renderAIUsage();if(orderId)await loadGallery(orderId);toast('Geração concluída.')}catch(e){toast(e.message||'Falha ao gerar.');$('aiResults').innerHTML=`<div class="empty">${h(e.message||'Falha ao gerar imagem.')}</div>`}finally{btn.disabled=false;btn.textContent='Gerar agora'}}
async function loadAIUsage(){const month=new Date().toISOString().slice(0,7)+'-01';const [{data:u},{data:p}]=await Promise.all([db.from('ai_usage_monthly').select('images_generated').eq('studio_id',sid).eq('month',month).maybeSingle(),db.from('plans').select('ai_image_limit').eq('id',ctx.studio.plan_id).single()]);aiUsage={used:Number(u?.images_generated||0),limit:Number(p?.ai_image_limit||0)};renderAIUsage()}
function renderAIUsage(){$('aiUsage').textContent=`Uso de IA: ${aiUsage.used} de ${aiUsage.limit||0} imagens neste mês`}
async function createPortal(){const orderId=$('galOrder').value;if(!orderId)return toast('Selecione um pedido.');try{const {data,error}=await db.functions.invoke('manage-client-portal',{body:{action:'create',orderId,expiresDays:30}});if(error)throw error;if(data?.error)throw new Error(data.error);const url=location.origin+data.relativeUrl;$('portalLinkBox').textContent=url;$('portalCopyBtn').disabled=false;toast('Link do cliente criado.')}catch(e){toast(e.message||'Falha ao criar link.')}}
async function uploadGallery(){const orderId=$('galOrder').value,p=$('galPreview').files[0],f=$('galFinal').files[0];if(!orderId||!p)return toast('Escolha o pedido e a prévia.');try{const base=`${sid}/${orderId}/gallery/${crypto.randomUUID()}`;const pp=await uploadFile(p,`${base}-preview.${(p.name.split('.').pop()||'jpg')}`);let fp=pp;if(f)fp=await uploadFile(f,`${base}-final.${(f.name.split('.').pop()||'jpg')}`);const {error}=await db.from('gallery_items').insert({studio_id:sid,order_id:orderId,label:p.name,source:'uploaded',kind:$('galKind').value,preview_path:pp,final_path:fp,mime_type:p.type,price:$('galKind').value==='extra'?Number($('galPrice').value||0):0,status:'preview',position:gallery.length});if(error)throw error;$('galPreview').value='';$('galFinal').value='';await loadGallery(orderId);toast('Foto publicada na galeria.')}catch(e){toast(e.message||'Falha no upload.')}}
async function loadGallery(orderId){if(!orderId)return;const [{data:g},{data:r}]=await Promise.all([db.from('gallery_items').select('*').eq('order_id',orderId).order('position'),db.from('client_references').select('*').eq('order_id',orderId).order('created_at',{ascending:false})]);gallery=g||[];const cards=[];for(const x of gallery){let url='';if(x.preview_path){const {data:s}=await db.storage.from('intorna-media').createSignedUrl(x.preview_path,900);url=s?.signedUrl||''}cards.push(`<div class="v6-photo">${url?`<img src="${url}">`:''}<div class="meta"><b>${h(x.label||'Foto')}</b><br><span class="v6-status">${h(x.kind)} • ${h(x.status)}</span>${x.kind==='extra'?`<p>${money(x.price)}</p>`:''}<div class="actions"><button class="btn ghost" onclick="IntornaV6.release('${x.id}')">${x.status==='draft'?'Publicar prévia':'Liberar final'}</button><button class="btn danger" onclick="IntornaV6.removeGallery('${x.id}')">Excluir</button></div></div></div>`)}$('galItems').innerHTML=cards.join('')||'<div class="empty">Nenhuma foto publicada.</div>';$('galRefs').innerHTML=(r||[]).map(x=>`<div class="library-item"><b>${h(x.original_name||'Referência')}</b><p>${h(x.note||'')}</p><small class="muted">${new Date(x.created_at).toLocaleString('pt-BR')}</small></div>`).join('')||'<div class="empty">Nenhuma referência recebida.</div>'}
async function release(id){const item=gallery.find(x=>x.id===id);await db.from('gallery_items').update({status:item?.status==='draft'?'preview':'released'}).eq('id',id);await loadGallery($('galOrder').value);toast('Foto liberada.')}
async function removeGallery(id){if(!confirm('Excluir esta foto da galeria?'))return;await db.from('gallery_items').delete().eq('id',id);await loadGallery($('galOrder').value)}
async function saveWhiteLabel(){if(ctx.studio.plan_id!=='studio')return toast('White Label é um recurso do plano Studio.');try{let logo=ctx.studio.settings?.white_label?.logo_path||null;const f=$('wlLogo').files[0];if(f)logo=await uploadFile(f,`${sid}/branding/${crypto.randomUUID()}-${f.name.replace(/[^a-z0-9._-]/gi,'_')}`);const settings={...(ctx.studio.settings||{}),white_label:{name:$('wlName').value.trim()||ctx.studio.name,color:$('wlColor').value,logo_path:logo}};const {error}=await db.from('studios').update({settings}).eq('id',sid);if(error)throw error;ctx.studio.settings=settings;toast('White Label salvo.')}catch(e){toast(e.message||'Falha ao salvar.')}}
async function loadTemplates(){const {data,error}=await db.from('shoot_templates').select('*').eq('active',true).order('sort_order');if(error)return;templates=(data||[]).filter(t=>!t.premium||ctx.studio.plan_id!=='free');$('templateList').innerHTML=templates.map(t=>`<div class="v6-template"><span class="tag">${h(t.category)}${t.premium?' • PREMIUM':''}</span><h3>${h(t.title)}</h3><p>${h(t.description||'')}</p><button class="btn primary" onclick="IntornaV6.useTemplate('${t.id}')">Usar modelo</button></div>`).join('')}
function useTemplate(id){const t=templates.find(x=>x.id===id);if(!t)return;const b=t.blueprint||{};gTema.value=t.title;gEstilo.value=b.estilo||gEstilo.value;gEmocao.value=b.emocao||gEmocao.value;if([...gCenario.options].some(o=>o.value===b.cenario))gCenario.value=b.cenario;gObs.value=`Sequência sugerida:\n${(b.shot_list||[]).map((x,i)=>`${i+1}. ${x}`).join('\n')}`;goPage('director');directorPlan();toast('Modelo aplicado ao AI Director.')}
function directorPlan(){const q=Math.max(1,Number(gQtd.value||6)),base=['Retrato fechado com foco absoluto no rosto','Meio corpo com postura natural','Corpo inteiro mostrando figurino e ambiente','Pose em movimento para variação real','Imagem editorial com composição de destaque','Close final com expressão conectada'];const lines=[];for(let i=0;i<q;i++)lines.push(`${i+1}. ${base[i%base.length]} — variar pose, enquadramento e microexpressão sem mudar a identidade.`);const box=$('v6DirectorPlan');box.style.display='block';box.textContent=`PLANO DE PRODUÇÃO\n\n${lines.join('\n')}\n\nCONSISTÊNCIA: manter a mesma identidade, idade aparente, pele, cabelo, corpo, figurino-base e linguagem de iluminação ao longo de toda a série.`}
function renderOpportunities(){const now=new Date(),rows=[];for(const c of state.clients){let score=0,reasons=[];const os=state.orders.filter(o=>o.clientId===c.id);if(os.some(o=>Number(o.extraOfferQty||0)>Number((o.extraSales||[]).reduce((a,s)=>a+Number(s.qty||0),0)))){score+=40;reasons.push('fotos extras disponíveis')}if(os.some(o=>o.payment!=='Pago')){score+=25;reasons.push('pagamento pendente')}if(os.some(o=>o.status==='Entregue')){score+=15;reasons.push('pós-venda')}if(c.importantDate){const d=new Date(c.importantDate+'T12:00:00');let next=new Date(now.getFullYear(),d.getMonth(),d.getDate());if(next<now)next.setFullYear(now.getFullYear()+1);const days=(next-now)/86400000;if(days<=30){score+=30;reasons.push(`data importante em ${Math.ceil(days)} dias`)}}if(score)rows.push({c,score,reasons})}rows.sort((a,b)=>b.score-a.score);$('oppList').innerHTML=rows.map(x=>`<div class="v6-opportunity"><span class="v6-score">${x.score} pts</span><b>${h(x.c.name)}</b><p>${h(x.reasons.join(' • '))}</p><button class="btn ghost" onclick="IntornaV6.whats('${x.c.id}')">Chamar no WhatsApp</button></div>`).join('')||'<div class="empty">Nenhuma oportunidade urgente agora.</div>'}
function whats(id){const c=getClient(id);if(!c?.whatsapp)return toast('Cliente sem WhatsApp.');window.open(`https://wa.me/55${String(c.whatsapp).replace(/\D/g,'')}`,'_blank')}
async function loadCosts(){const {data}=await db.from('cost_entries').select('*').eq('studio_id',sid).order('created_at',{ascending:false});costs=data||[]}
async function addCost(){const orderId=$('costOrder').value,v=Number($('costValue').value||0);if(!orderId||v<=0)return toast('Informe pedido e valor.');const {error}=await db.from('cost_entries').insert({studio_id:sid,order_id:orderId,category:$('costCategory').value,description:$('costDesc').value.trim(),amount:v});if(error)return toast(error.message);$('costValue').value='';$('costDesc').value='';await loadCosts();renderProfit();toast('Custo registrado.')}
function renderProfit(){const oid=$('costOrder')?.value;if(!oid)return;const o=getOrder(oid);if(!o)return;const cost=costs.filter(x=>x.order_id===oid).reduce((a,x)=>a+Number(x.amount||0),0),rev=Number(o.total||0),profit=rev-cost;$('profitBox').innerHTML=`<p>Receita do pedido: <b>${money(rev)}</b></p><p>Custos registrados: <b>${money(cost)}</b></p><div class="v6-profit ${profit>=0?'positive':'negative'}">${money(profit)}</div><p class="muted">Margem: ${rev?((profit/rev)*100).toFixed(1):0}%</p>`}
async function loadReferral(){try{const {data,error}=await db.functions.invoke('referral-program',{body:{studioId:sid}});if(error)throw error;if(data?.error)throw new Error(data.error);$('refCode').textContent=data.code||'—';const refs=data.referrals||[],q=refs.filter(x=>['qualified','rewarded'].includes(x.status)).length;$('refStats').innerHTML=`<p><b>${refs.length}</b> indicações realizadas</p><p><b>${q}</b> qualificadas</p><p>Crédito potencial: <b>${money(q*Number(data.reward_value||0))}</b></p>`}catch(e){$('refCode').textContent='Não disponível';$('refStats').innerHTML=`<p>${h(e.message)}</p>`}}
function copyReferral(){const code=$('refCode').textContent;if(!code||code==='—')return;navigator.clipboard.writeText(`Conheça o Intorná Pixels. Crie seu estúdio e use meu código de indicação: ${code}`).then(()=>toast('Convite copiado.'))}
window.IntornaV6={release,removeGallery,useTemplate,whats};inject();
})();
