(function(){
  'use strict';
  const STATUS={draft:'Rascunho',sent:'Enviado',accepted:'Aceito',rejected:'Recusado',expired:'Expirado',converted:'Convertido'};
  const $=id=>document.getElementById(id);
  const h=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let editing='',filter='all',search='';

  function inject(){
    if($('orcamentos'))return;
    state.config.quotes=Array.isArray(state.config.quotes)?state.config.quotes:[];
    const nav=document.querySelector('.nav'),before=nav?.querySelector('[data-page="pedidos"]');
    if(nav){const b=document.createElement('button');b.dataset.page='orcamentos';b.innerHTML='<span class="ico">▤</span><span class="label">Orçamentos</span><span class="v11-nav-count" id="v11NavCount">0</span>';b.onclick=()=>{render();goPage('orcamentos')};nav.insertBefore(b,before)}
    document.querySelector('.container')?.insertAdjacentHTML('beforeend',page());
    const link=document.createElement('link');link.rel='stylesheet';link.href='styles-v11.css';document.head.appendChild(link);
    bind();const previousSave=save;save=function(){previousSave();render()};render();resetForm();
  }
  function page(){return `<section class="page" id="orcamentos">
    <div class="v11-head"><div><span>PROPOSTAS COMERCIAIS</span><h2>Orçamentos que viram pedidos.</h2><p>Calcule, envie, acompanhe e converta cada proposta sem redigitar informações.</p></div><button class="btn gold" id="v11New">+ Novo orçamento</button></div>
    <div class="v11-kpis"><article><small>Em negociação</small><b id="v11Open">0</b></article><article><small>Aceitos</small><b id="v11Accepted">0</b></article><article><small>Convertidos</small><b id="v11Converted">0</b></article><article><small>Valor em aberto</small><b id="v11Pipeline">R$ 0,00</b></article></div>
    <div class="v11-layout">
      <form id="v11Form" class="v11-editor"><div class="v11-editor-title"><div><span id="v11FormEyebrow">NOVA PROPOSTA</span><h3 id="v11FormTitle">Monte o orçamento</h3></div><button type="button" class="v11-reset" id="v11Reset">Limpar</button></div>
        <label>Cliente</label><select id="v11Client" required></select>
        <div class="v11-form-grid"><div><label>Pacote</label><select id="v11Package">${PACKAGES.filter(x=>x.active).map(x=>`<option value="${x.id}">${h(x.name)} — ${x.photos} fotos</option>`).join('')}</select></div><div><label>Tipo de ensaio</label><select id="v11Type">${TYPES.map(x=>`<option>${h(x)}</option>`).join('')}</select></div><div><label>Formato</label><select id="v11Format"><option>4:5</option><option>9:16</option><option>1:1</option><option>16:9</option></select></div><div><label>Validade</label><input id="v11Expiry" type="date" required></div><div><label>Desconto</label><div class="v11-money-input"><span>R$</span><input id="v11Discount" type="number" min="0" step="0.01" value="0"></div></div><div><label>Status</label><select id="v11Status">${Object.entries(STATUS).filter(([k])=>k!=='converted').map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div></div>
        <label>Serviços adicionais</label><div class="v11-extras">${EXTRAS.map(x=>`<label><input type="checkbox" class="v11-extra" value="${x.id}"><span><b>${h(x.name)}</b><small>${money(x.price)}</small></span></label>`).join('')}</div>
        <label>Observações e condições</label><textarea id="v11Notes" rows="3" placeholder="Ex.: pagamento via Pix, prazo após o envio das fotos..."></textarea>
        <div class="v11-total"><div><small>Subtotal</small><span id="v11Subtotal">R$ 0,00</span></div><div><small>Desconto</small><span id="v11DiscountView">− R$ 0,00</span></div><div class="grand"><small>Total da proposta</small><b id="v11Total">R$ 0,00</b></div></div>
        <button class="btn primary v11-save" type="submit" id="v11Save">Salvar orçamento</button>
      </form>
      <div class="v11-list"><div class="v11-toolbar"><label><span>⌕</span><input id="v11Search" placeholder="Buscar cliente ou ensaio"></label><select id="v11Filter"><option value="all">Todos os status</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div id="v11Quotes"></div></div>
    </div>
  </section>`}
  function bind(){
    $('v11Form').onsubmit=e=>{e.preventDefault();store()};$('v11New').onclick=()=>{resetForm();goPage('orcamentos');$('v11Client').focus()};$('v11Reset').onclick=resetForm;
    ['v11Package','v11Discount'].forEach(id=>$(id).addEventListener('input',calculate));document.querySelectorAll('.v11-extra').forEach(x=>x.onchange=calculate);
    $('v11Search').oninput=e=>{search=e.target.value.toLowerCase().trim();renderList()};$('v11Filter').onchange=e=>{filter=e.target.value;renderList()};
  }
  function resetForm(clientId=''){
    editing='';$('v11Form').reset();fillClients(clientId);$('v11Expiry').value=futureDate(7);$('v11Discount').value='0';$('v11FormEyebrow').textContent='NOVA PROPOSTA';$('v11FormTitle').textContent='Monte o orçamento';$('v11Save').textContent='Salvar orçamento';calculate();
  }
  function fillClients(selected=''){const current=selected||$('v11Client')?.value||'';$('v11Client').innerHTML=state.clients.length?state.clients.map(c=>`<option value="${c.id}">${h(c.name)}</option>`).join(''):'<option value="">Cadastre um cliente primeiro</option>';if(current&&getClient(current))$('v11Client').value=current}
  function futureDate(days){const d=new Date();d.setDate(d.getDate()+days);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
  function selectedExtras(){return [...document.querySelectorAll('.v11-extra:checked')].map(x=>x.value)}
  function values(){const pkg=getPackage($('v11Package').value),extras=selectedExtras(),subtotal=Number(pkg.price)+extras.reduce((n,id)=>n+Number(EXTRAS.find(x=>x.id===id)?.price||0),0),discount=Math.min(subtotal,Math.max(0,Number($('v11Discount').value||0)));return {pkg,extras,subtotal,discount,total:subtotal-discount}}
  function calculate(){if(!$('v11Subtotal'))return;const v=values();$('v11Subtotal').textContent=money(v.subtotal);$('v11DiscountView').textContent=`− ${money(v.discount)}`;$('v11Total').textContent=money(v.total)}
  function store(){
    if(!$('v11Client').value)return toast('Cadastre ou selecione um cliente.');const v=values(),now=new Date().toISOString(),old=state.config.quotes.find(x=>x.id===editing);
    const quote={id:old?.id||uid('orc'),number:old?.number||nextNumber(),clientId:$('v11Client').value,packageId:v.pkg.id,type:$('v11Type').value,format:$('v11Format').value,expiry:$('v11Expiry').value,discount:v.discount,extras:v.extras,subtotal:v.subtotal,total:v.total,status:old?.status==='converted'?'converted':$('v11Status').value,notes:$('v11Notes').value.trim(),createdAt:old?.createdAt||now,updatedAt:now,orderId:old?.orderId||null};
    if(old)state.config.quotes=state.config.quotes.map(x=>x.id===old.id?quote:x);else state.config.quotes.unshift(quote);
    if(window.IntornaCRM){const m=IntornaCRM.getMeta(quote.clientId);if(!['fechado','perdido'].includes(m.stage))IntornaCRM.setMeta(quote.clientId,{stage:quote.status==='accepted'?'negociacao':'orcamento',expectedValue:quote.total})}
    save();resetForm(quote.clientId);toast(old?'Orçamento atualizado.':'Orçamento criado.');
  }
  function nextNumber(){const year=new Date().getFullYear(),numbers=state.config.quotes.map(x=>Number(String(x.number||'').split('-').pop())||0);return `ORC-${year}-${String(Math.max(0,...numbers)+1).padStart(4,'0')}`}
  function expireQuotes(){const now=new Date().toISOString().slice(0,10);state.config.quotes.forEach(q=>{if(!['accepted','rejected','converted'].includes(q.status)&&q.expiry&&q.expiry<now)q.status='expired'})}
  function currentQuotes(){expireQuotes();return state.config.quotes.filter(q=>{const c=getClient(q.clientId),text=`${q.number} ${c?.name||''} ${q.type||''}`.toLowerCase();return(filter==='all'||q.status===filter)&&(!search||text.includes(search))})}
  function render(){if(!$('orcamentos'))return;fillClients();expireQuotes();const quotes=state.config.quotes,open=quotes.filter(x=>['draft','sent'].includes(x.status));$('v11Open').textContent=open.length;$('v11Accepted').textContent=quotes.filter(x=>x.status==='accepted').length;$('v11Converted').textContent=quotes.filter(x=>x.status==='converted').length;$('v11Pipeline').textContent=money(open.reduce((n,x)=>n+Number(x.total||0),0));const attention=quotes.filter(x=>['draft','sent','accepted'].includes(x.status)).length;$('v11NavCount').textContent=attention;$('v11NavCount').style.display=attention?'inline-grid':'none';renderList()}
  function renderList(){const box=$('v11Quotes'),quotes=currentQuotes();box.innerHTML=quotes.length?quotes.map(card).join(''):'<div class="v11-empty"><b>Nenhum orçamento encontrado.</b><span>Crie uma proposta para começar a acompanhar as negociações.</span></div>'}
  function card(q){const c=getClient(q.clientId),pkg=getPackage(q.packageId),expired=q.expiry&&q.expiry<new Date().toISOString().slice(0,10);return `<article class="v11-card"><header><div><span>${h(q.number)}</span><h3>${h(c?.name||'Cliente removido')}</h3><p>${h(q.type)} • ${h(pkg.name)} • ${pkg.photos} fotos</p></div><em class="v11-status ${q.status}">${h(STATUS[q.status]||q.status)}</em></header><div class="v11-card-meta"><div><small>Total</small><b>${money(q.total)}</b></div><div><small>Validade</small><b class="${expired?'overdue':''}">${date(q.expiry)}</b></div><div><small>Atualizado</small><b>${date(String(q.updatedAt).slice(0,10))}</b></div></div><footer><button onclick="IntornaQuotes.whats('${q.id}')">WhatsApp</button><button onclick="IntornaQuotes.print('${q.id}')">Imprimir/PDF</button><button onclick="IntornaQuotes.edit('${q.id}')">Editar</button><button onclick="IntornaQuotes.remove('${q.id}')">Excluir</button><select aria-label="Alterar status" onchange="IntornaQuotes.status('${q.id}',this.value)">${Object.entries(STATUS).filter(([k])=>k!=='converted'||q.status==='converted').map(([k,v])=>`<option value="${k}" ${q.status===k?'selected':''}>${v}</option>`).join('')}</select>${q.status!=='converted'?`<button class="convert" onclick="IntornaQuotes.convert('${q.id}')">Converter em pedido</button>`:`<button onclick="newOrderFor('${q.clientId}')">Ver pedidos</button>`}</footer></article>`}
  function date(v){if(!v)return '—';return new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR')}
  function edit(id){const q=state.config.quotes.find(x=>x.id===id);if(!q)return;editing=id;fillClients(q.clientId);$('v11Package').value=q.packageId;$('v11Type').value=q.type;$('v11Format').value=q.format;$('v11Expiry').value=q.expiry;$('v11Discount').value=q.discount||0;$('v11Status').value=q.status==='converted'?'accepted':q.status;$('v11Notes').value=q.notes||'';document.querySelectorAll('.v11-extra').forEach(x=>x.checked=(q.extras||[]).includes(x.value));$('v11FormEyebrow').textContent=q.number;$('v11FormTitle').textContent='Editar orçamento';$('v11Save').textContent='Atualizar orçamento';calculate();goPage('orcamentos');$('v11Form').scrollIntoView({behavior:'smooth',block:'start'})}
  function setStatus(id,value){const q=state.config.quotes.find(x=>x.id===id);if(!q||!STATUS[value])return;q.status=value;q.updatedAt=new Date().toISOString();if(window.IntornaCRM&&value==='accepted')IntornaCRM.setMeta(q.clientId,{stage:'negociacao',expectedValue:q.total});save();toast(`Status: ${STATUS[value]}.`)}
  function remove(id){const q=state.config.quotes.find(x=>x.id===id);if(!q||!confirm(`Excluir o orçamento ${q.number}?`))return;state.config.quotes=state.config.quotes.filter(x=>x.id!==id);save();toast('Orçamento excluído.')}
  function message(q){const c=getClient(q.clientId),pkg=getPackage(q.packageId),extras=(q.extras||[]).map(id=>EXTRAS.find(x=>x.id===id)?.name).filter(Boolean);return `Olá, ${(c?.name||'cliente').split(' ')[0]}! 😊\n\nPreparei seu orçamento ${q.number}:\n• ${q.type}\n• Pacote ${pkg.name} — ${pkg.photos} fotos\n• Formato ${q.format}${extras.length?`\n• Adicionais: ${extras.join(', ')}`:''}\n\nTotal: ${money(q.total)}\nVálido até: ${date(q.expiry)}\n\n${q.notes?`${q.notes}\n\n`:''}Se estiver de acordo, me confirme por aqui para transformarmos em pedido. ✨`}
  function whats(id){const q=state.config.quotes.find(x=>x.id===id),c=q&&getClient(q.clientId);if(!q||!c?.whatsapp)return toast('Cliente sem WhatsApp cadastrado.');if(q.status==='draft')q.status='sent';q.updatedAt=new Date().toISOString();save();window.open(`https://wa.me/55${String(c.whatsapp).replace(/\D/g,'')}?text=${encodeURIComponent(message(q))}`,'_blank','noopener')}
  function printQuote(id){const q=state.config.quotes.find(x=>x.id===id);if(!q)return;const c=getClient(q.clientId),pkg=getPackage(q.packageId),extras=(q.extras||[]).map(x=>EXTRAS.find(e=>e.id===x)).filter(Boolean),w=window.open('','_blank');if(!w)return toast('Permita pop-ups para imprimir o orçamento.');w.opener=null;w.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${h(q.number)}</title><style>body{font:15px Arial;color:#172033;margin:0;padding:42px}header{display:flex;justify-content:space-between;border-bottom:3px solid #f0b429;padding-bottom:22px}h1{font-size:26px;margin:0}small{color:#667085}.brand{font-weight:900;color:#0b132b}.box{margin:28px 0;padding:20px;background:#f8fafc;border-radius:12px}.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e5e7eb}.total{font-size:22px;font-weight:900}.notes{white-space:pre-wrap}.footer{margin-top:35px;color:#667085;font-size:12px}@media print{body{padding:18px}}</style></head><body><header><div><div class="brand">${h(state.config.brand||'Meu Estúdio')}</div><small>${h(state.config.whatsapp||'')}</small></div><div style="text-align:right"><h1>ORÇAMENTO</h1><b>${h(q.number)}</b></div></header><div class="box"><b>Cliente: ${h(c?.name||'Cliente')}</b><p>${h(c?.email||'')} ${c?.whatsapp?`• ${h(c.whatsapp)}`:''}</p><small>Proposta válida até ${date(q.expiry)}</small></div><h2>${h(q.type)}</h2><div class="row"><span>Pacote ${h(pkg.name)} — ${pkg.photos} fotos — formato ${h(q.format)}</span><b>${money(pkg.price)}</b></div>${extras.map(x=>`<div class="row"><span>${h(x.name)}</span><b>${money(x.price)}</b></div>`).join('')}${q.discount?`<div class="row"><span>Desconto</span><b>− ${money(q.discount)}</b></div>`:''}<div class="row total"><span>Total</span><b>${money(q.total)}</b></div>${q.notes?`<div class="box notes"><b>Condições</b><p>${h(q.notes)}</p></div>`:''}<div class="footer">Proposta gerada pelo Intorná Pixels em ${new Date().toLocaleDateString('pt-BR')}.</div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
  function convert(id){const q=state.config.quotes.find(x=>x.id===id);if(!q||q.status==='converted')return;if(thisMonthOrders().length>=getPlan().limit)return toast('Limite mensal do plano atingido.');if(!confirm(`Converter ${q.number} em pedido?`))return;const orderId=uid('ord');state.orders.push({id:orderId,clientId:q.clientId,packageId:q.packageId,type:q.type,format:q.format,payment:'Pendente',paymentMethod:'Pix',status:'Aguardando fotos',deadline:generateDeadline(),extras:q.extras||[],notes:`Originado do orçamento ${q.number}${q.notes?`\n${q.notes}`:''}`,extraOfferQty:3,extraStrategy:'combo',watermarkExtras:true,extraSales:[],total:Number(q.total||0),createdAt:new Date().toISOString()});q.status='converted';q.orderId=orderId;q.updatedAt=new Date().toISOString();window.IntornaCRM?.setMeta(q.clientId,{stage:'fechado',expectedValue:q.total});save();toast('Orçamento convertido em pedido.');goPage('pedidos')}
  function newFor(clientId){resetForm(clientId);goPage('orcamentos');$('v11Client').focus()}
  window.IntornaQuotes={newFor,edit,status:setStatus,remove,whats,print:printQuote,convert,render};inject();
})();
