'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})};
const dateValue=v=>v?new Date(v).toISOString().slice(0,10):'';
let ctx=null,data={studios:[],profiles:[],plans:[],subscriptions:[],payments:[],coupons:[],notices:[],tickets:[],logs:[],usage:[],settings:null};
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function toggleMenu(){$('sidebar').classList.toggle('open')} window.toggleMenu=toggleMenu;
function goPage(id){const target=typeof id==='string'?document.getElementById(id):null;if(!target||!target.classList.contains('page')){console.warn('Intorná Admin: navegação ignorada para página inválida.',id);return false}document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p===target));document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const b=[...document.querySelectorAll('.nav button[data-page]')].find(x=>x.dataset.page===id);$('pageTitle').textContent=b?.querySelector('.label')?.textContent||'Central';$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});return true} window.goPage=goPage;
async function logout(){await IntornaCloud.signOut()} window.logout=logout;
function statusPill(status){const map={active:['Ativo','ok'],trial:['Teste','warn'],blocked:['Bloqueado','bad'],cancelled:['Cancelado','bad'],paid:['Pago','ok'],pending:['Pendente','warn'],overdue:['Vencido','bad'],free:['Gratuito',''],confirmed:['Confirmado','ok'],received:['Recebido','ok']};const x=map[status]||[status||'—',''];return `<span class="pill ${x[1]}">${esc(x[0])}</span>`}
function profileFor(uid){return data.profiles.find(p=>p.id===uid)||{full_name:'',email:''}}
function planFor(id){return data.plans.find(p=>p.id===id)||data.plans[0]||{name:id||'—',price:0,order_limit:0}}
function usageFor(sid){const month=new Date().toISOString().slice(0,7);return data.usage.find(u=>u.studio_id===sid&&String(u.month).slice(0,7)===month)||{orders_count:0,clients_count:0}}
async function loadData(){
  const q=[
    IntornaCloud.client.from('studios').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('profiles').select('*'),
    IntornaCloud.client.from('plans').select('*').order('sort_order'),
    IntornaCloud.client.from('subscriptions').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('payments').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('coupons').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('announcements').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('support_tickets').select('*').order('created_at',{ascending:false}),
    IntornaCloud.client.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200),
    IntornaCloud.client.from('usage_monthly').select('*'),
    IntornaCloud.client.from('platform_settings').select('*').eq('id',1).maybeSingle()
  ];
  const r=await Promise.all(q);for(const x of r)if(x.error)throw x.error;
  [data.studios,data.profiles,data.plans,data.subscriptions,data.payments,data.coupons,data.notices,data.tickets,data.logs,data.usage]=r.slice(0,10).map(x=>x.data||[]);data.settings=r[10].data||{};
}
function renderOverview(){const active=data.studios.filter(s=>s.status==='active').length,trial=data.studios.filter(s=>s.status==='trial').length,overdue=data.studios.filter(s=>s.billing_status==='overdue').length,mrr=data.studios.filter(s=>s.status==='active'&&s.billing_status==='paid').reduce((n,s)=>n+Number(planFor(s.plan_id).price||0),0);$('kpiActive').textContent=active;$('kpiMrr').textContent=money(mrr);$('kpiTrial').textContent=trial;$('kpiOverdue').textContent=overdue;const totalOrders=data.usage.reduce((n,u)=>n+Number(u.orders_count||0),0);$('usageSummary').innerHTML=`<p><b>${data.studios.length}</b> contas cadastradas</p><p><b>${totalOrders}</b> ensaios contabilizados</p><p><b>${data.tickets.filter(t=>t.status!=='closed').length}</b> chamados abertos</p>`;const groups={};data.studios.forEach(s=>groups[s.plan_id]=(groups[s.plan_id]||0)+1);$('planSummary').innerHTML=data.plans.map(p=>{const n=groups[p.id]||0,pct=data.studios.length?n/data.studios.length*100:0;return `<div style="margin:12px 0"><div class="row" style="justify-content:space-between"><b>${esc(p.name)}</b><span>${n}</span></div><div class="progress"><span style="width:${pct}%"></span></div></div>`}).join('')||'<div class="empty">Sem dados.</div>';$('recentLogs').innerHTML=data.logs.slice(0,8).map(l=>`<div class="notice"><b>${esc(l.event)}</b><br><small class="muted">${fmt(l.created_at)}</small></div>`).join('')||'<div class="empty">Sem atividade.</div>'}
function populatePlanSelect(){const old=$('sPlan').value;$('sPlan').innerHTML=data.plans.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('');if(old&&data.plans.some(p=>p.id===old))$('sPlan').value=old}
function renderStudios(){populatePlanSelect();$('studiosBody').innerHTML=data.studios.length?data.studios.map(s=>{const p=planFor(s.plan_id),prof=profileFor(s.owner_user_id),u=usageFor(s.id),limit=p.order_limit>=999999?'∞':p.order_limit;return `<tr><td><b>${esc(s.name)}</b><br><small>${esc(prof.full_name||'Responsável')} • ${esc(prof.email||'')}</small></td><td>${esc(p.name)}<br><small>${money(p.price)}/mês</small></td><td>${statusPill(s.status)}</td><td>${statusPill(s.billing_status)}</td><td>${u.orders_count} / ${limit}</td><td>${fmt(s.next_billing_at)}</td><td><div class="row"><button class="btn ghost" onclick="editStudio('${s.id}')">Editar</button><button class="btn primary" onclick="openOperation('${s.id}')">Operação</button><button class="btn ${s.status==='blocked'?'success':'danger'}" onclick="toggleStudio('${s.id}')">${s.status==='blocked'?'Liberar':'Bloquear'}</button><button class="btn outline" onclick="resetStudioPassword('${s.id}')">Senha</button><button class="btn danger" onclick="deleteStudio('${s.id}')">Excluir</button></div></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Nenhum estúdio cadastrado.</td></tr>'}
function renderSubscriptions(){$('subscriptionsBody').innerHTML=data.studios.length?data.studios.map(s=>{const p=planFor(s.plan_id);return `<tr><td><b>${esc(s.name)}</b></td><td><select onchange="changePlan('${s.id}',this.value)">${data.plans.map(x=>`<option value="${x.id}" ${x.id===s.plan_id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></td><td>${money(p.price)}</td><td>${statusPill(s.status)}</td><td>${statusPill(s.billing_status)}</td><td>${fmt(s.next_billing_at)}</td><td><button class="btn success" onclick="markPaid('${s.id}')">Pago</button> <button class="btn danger" onclick="markOverdue('${s.id}')">Vencido</button> <button class="btn ghost" onclick="extendBilling('${s.id}')">+30 dias</button></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Sem assinaturas.</td></tr>'}
function renderPlans(){$('plansGrid').innerHTML=data.plans.map(p=>`<div class="plan-card"><div class="row" style="justify-content:space-between"><h3>${esc(p.name)}</h3>${statusPill(p.active?'active':'cancelled')}</div><label>Mensalidade</label><input id="plan_price_${p.id}" type="number" step="0.01" value="${Number(p.price)}"><label>Ensaios/mês</label><input id="plan_orders_${p.id}" type="number" value="${Number(p.order_limit)}"><label>Clientes</label><input id="plan_clients_${p.id}" type="number" value="${Number(p.client_limit)}"><label>Usuários</label><input id="plan_users_${p.id}" type="number" value="${Number(p.user_limit)}"><label>Recursos</label><textarea id="plan_features_${p.id}">${esc((p.features||[]).join('\n'))}</textarea><div class="row"><button class="btn primary" onclick="savePlan('${p.id}')">Salvar</button><button class="btn ghost" onclick="togglePlan('${p.id}')">${p.active?'Ocultar':'Ativar'}</button></div></div>`).join('')}
function renderCoupons(){$('couponsBody').innerHTML=data.coupons.length?data.coupons.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${c.discount_type==='percent'?`${Number(c.value)}%`:money(c.value)}</td><td>${c.redemptions||0} / ${c.max_redemptions||'∞'}</td><td>${fmt(c.expires_at)}</td><td>${statusPill(c.active?'active':'cancelled')}</td><td><button class="btn ghost" onclick="toggleCoupon('${c.id}')">${c.active?'Desativar':'Ativar'}</button> <button class="btn danger" onclick="deleteCoupon('${c.id}')">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Nenhum cupom.</td></tr>'}
function renderNotices(){$('noticesList').innerHTML=data.notices.length?data.notices.map(n=>`<div class="notice"><div class="row" style="justify-content:space-between"><div><b>${esc(n.title)}</b><br><small>${esc(n.audience)} • ${fmt(n.created_at)}</small></div><div><button class="btn ghost" onclick="toggleNotice('${n.id}')">${n.active?'Ocultar':'Ativar'}</button> <button class="btn danger" onclick="deleteNotice('${n.id}')">Excluir</button></div></div><p>${esc(n.body)}</p></div>`).join(''):'<div class="empty">Nenhum aviso.</div>'}
function renderTickets(){$('ticketsBody').innerHTML=data.tickets.length?data.tickets.map(t=>{const s=data.studios.find(x=>x.id===t.studio_id);return `<tr><td>${fmt(t.created_at)}</td><td>${esc(s?.name||'—')}</td><td><b>${esc(t.subject)}</b></td><td>${esc(t.message)}${t.admin_response?`<br><small><b>Resposta:</b> ${esc(t.admin_response)}</small>`:''}</td><td>${esc(t.priority||'medium')}</td><td>${statusPill(t.status==='closed'?'paid':t.status==='in_progress'?'pending':'trial')}</td><td><button class="btn primary" onclick="advanceTicket('${t.id}')">Avançar</button> <button class="btn ghost" onclick="respondTicket('${t.id}')">Responder</button></td></tr>`}).join(''):'<tr><td colspan="7" class="empty">Nenhum chamado.</td></tr>'}
function renderLogs(){$('logsBody').innerHTML=data.logs.length?data.logs.map(l=>{const s=data.studios.find(x=>x.id===l.studio_id);return `<tr><td>${fmt(l.created_at)}</td><td>${esc(l.event)}</td><td>${esc(s?.name||'Plataforma')}</td><td><small>${esc(JSON.stringify(l.payload||{}))}</small></td></tr>`}).join(''):'<tr><td colspan="4" class="empty">Sem logs.</td></tr>'}
function renderSettings(){const s=data.settings||{},p=profileFor(ctx.user.id);$('cfgBrand').value=s.brand||'Intorná Pixels';$('cfgEmail').value=s.support_email||'';$('cfgWhatsapp').value=s.support_whatsapp||'';$('cfgPix').value=s.pix||'';$('cfgTrial').value=s.trial_days??7;$('cfgMaintenance').value=String(!!s.maintenance);$('cfgMaintenanceMessage').value=s.maintenance_message||'';$('admName').value=p.full_name||ctx.user.user_metadata?.full_name||'';$('admEmail').value=p.email||ctx.user.email||'';$('admPassword').value='';$('adminName').textContent=p.full_name||'Administrador'}
function renderAll(){renderOverview();renderStudios();renderSubscriptions();renderPlans();renderCoupons();renderNotices();renderTickets();renderLogs();renderSettings()}
async function refresh(msg){try{await loadData();renderAll();if(msg)toast(msg)}catch(e){console.error(e);toast(e.message||'Falha ao atualizar dados.')}}
function clearStudioForm(){$('studioForm').reset();$('sId').value='';$('sPassword').required=true;$('sPassword').value='';$('studioFormTitle').textContent='Novo estúdio';populatePlanSelect()} window.clearStudioForm=clearStudioForm;
function editStudio(id){const s=data.studios.find(x=>x.id===id);if(!s)return;const p=profileFor(s.owner_user_id);$('sId').value=s.id;$('sName').value=s.name;$('sOwner').value=p.full_name||'';$('sEmail').value=p.email||'';$('sPassword').value='';$('sPassword').required=false;$('sWhatsapp').value=s.whatsapp||'';$('sCity').value=s.city||'';$('sPlan').value=s.plan_id;$('sStatus').value=s.status;$('sBilling').value=s.billing_status;$('sNextBilling').value=dateValue(s.next_billing_at);$('sNotes').value=s.settings?.admin_notes||'';$('studioFormTitle').textContent='Editar estúdio';window.scrollTo({top:0,behavior:'smooth'})} window.editStudio=editStudio;
function openOperation(id){localStorage.setItem('intorna_impersonate_studio',id);location.href='/app/'} window.openOperation=openOperation;
async function toggleStudio(id){const s=data.studios.find(x=>x.id===id);await IntornaCloud.adminAction('update_studio',{studio_id:id,status:s.status==='blocked'?'active':'blocked'});await refresh('Status atualizado.')} window.toggleStudio=toggleStudio;
async function resetStudioPassword(id){const pw=prompt('Nova senha (mínimo 8 caracteres):','');if(!pw)return;await IntornaCloud.adminAction('reset_password',{studio_id:id,password:pw});toast('Senha atualizada.')} window.resetStudioPassword=resetStudioPassword;
async function deleteStudio(id){const s=data.studios.find(x=>x.id===id);if(!s||!confirm(`Excluir ${s.name} e os dados do estúdio?`))return;await IntornaCloud.adminAction('delete_studio',{studio_id:id,delete_owner_user:false});await refresh('Estúdio excluído.')} window.deleteStudio=deleteStudio;
async function changePlan(id,plan_id){await IntornaCloud.adminAction('update_studio',{studio_id:id,plan_id});await refresh('Plano atualizado.')} window.changePlan=changePlan;
async function markPaid(id){const d=new Date();d.setDate(d.getDate()+30);await IntornaCloud.adminAction('update_studio',{studio_id:id,billing_status:'paid',status:'active',next_billing_at:d.toISOString()});await refresh('Pagamento confirmado.')} window.markPaid=markPaid;
async function markOverdue(id){await IntornaCloud.adminAction('update_studio',{studio_id:id,billing_status:'overdue'});await refresh('Marcado como vencido.')} window.markOverdue=markOverdue;
async function extendBilling(id){const s=data.studios.find(x=>x.id===id),d=s?.next_billing_at?new Date(s.next_billing_at):new Date();d.setDate(d.getDate()+30);await IntornaCloud.adminAction('update_studio',{studio_id:id,next_billing_at:d.toISOString()});await refresh('Vencimento prorrogado.')} window.extendBilling=extendBilling;
async function savePlan(id){const updates={price:Number($(`plan_price_${id}`).value||0),order_limit:Number($(`plan_orders_${id}`).value||0),client_limit:Number($(`plan_clients_${id}`).value||0),user_limit:Number($(`plan_users_${id}`).value||1),features:$(`plan_features_${id}`).value.split('\n').map(x=>x.trim()).filter(Boolean)};const {error}=await IntornaCloud.client.from('plans').update(updates).eq('id',id);if(error)throw error;await refresh('Plano salvo.')} window.savePlan=savePlan;
async function togglePlan(id){const p=data.plans.find(x=>x.id===id);const {error}=await IntornaCloud.client.from('plans').update({active:!p.active}).eq('id',id);if(error)throw error;await refresh()} window.togglePlan=togglePlan;
async function toggleCoupon(id){const c=data.coupons.find(x=>x.id===id);const {error}=await IntornaCloud.client.from('coupons').update({active:!c.active}).eq('id',id);if(error)throw error;await refresh()} window.toggleCoupon=toggleCoupon;
async function deleteCoupon(id){if(!confirm('Excluir este cupom?'))return;const {error}=await IntornaCloud.client.from('coupons').delete().eq('id',id);if(error)throw error;await refresh('Cupom excluído.')} window.deleteCoupon=deleteCoupon;
async function toggleNotice(id){const n=data.notices.find(x=>x.id===id);const {error}=await IntornaCloud.client.from('announcements').update({active:!n.active}).eq('id',id);if(error)throw error;await refresh()} window.toggleNotice=toggleNotice;
async function deleteNotice(id){const {error}=await IntornaCloud.client.from('announcements').delete().eq('id',id);if(error)throw error;await refresh('Aviso excluído.')} window.deleteNotice=deleteNotice;
async function advanceTicket(id){const t=data.tickets.find(x=>x.id===id),flow=['open','in_progress','closed'],status=flow[(flow.indexOf(t.status)+1)%flow.length];await IntornaCloud.adminAction('ticket_update',{ticket_id:id,status});await refresh('Chamado atualizado.')} window.advanceTicket=advanceTicket;
async function respondTicket(id){const t=data.tickets.find(x=>x.id===id);const response=prompt('Resposta ao estúdio:',t?.admin_response||'');if(response===null)return;await IntornaCloud.adminAction('ticket_update',{ticket_id:id,admin_response:response,status:'in_progress'});await refresh('Resposta registrada.')} window.respondTicket=respondTicket;
async function saveAdminCredentials(){const full_name=$('admName').value.trim(),email=$('admEmail').value.trim(),password=$('admPassword').value;const {error:pErr}=await IntornaCloud.client.from('profiles').update({full_name,email}).eq('id',ctx.user.id);if(pErr)throw pErr;const authUpdate={data:{full_name}};if(email&&email!==ctx.user.email)authUpdate.email=email;if(password)authUpdate.password=password;const {error:aErr}=await IntornaCloud.client.auth.updateUser(authUpdate);if(aErr)throw aErr;await refresh(email!==ctx.user.email?'Dados salvos. Confirme o novo e-mail se solicitado.':'Acesso atualizado.')} window.saveAdminCredentials=saveAdminCredentials;
function exportPlatform(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`intorna-pixels-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)} window.exportPlatform=exportPlatform;
function importPlatform(){toast('Importação direta será liberada em uma ferramenta de migração segura.')} window.importPlatform=importPlatform;
function resetPlatform(){toast('Restauração destrutiva está bloqueada na versão online.')} window.resetPlatform=resetPlatform;
function bind(){document.querySelectorAll('.nav button[data-page]:not([data-action])').forEach(b=>b.onclick=()=>goPage(b.dataset.page));$('studioForm').onsubmit=async e=>{e.preventDefault();try{const id=$('sId').value,payload={name:$('sName').value.trim(),owner_name:$('sOwner').value.trim(),email:$('sEmail').value.trim(),password:$('sPassword').value,whatsapp:$('sWhatsapp').value.trim(),city:$('sCity').value.trim(),plan_id:$('sPlan').value,status:$('sStatus').value,billing_status:$('sBilling').value,next_billing_at:$('sNextBilling').value?new Date(`${$('sNextBilling').value}T12:00:00`).toISOString():null,admin_notes:$('sNotes').value.trim()};if(id)await IntornaCloud.adminAction('update_studio',{studio_id:id,...payload});else await IntornaCloud.adminAction('create_studio',{...payload,trial_days:Number(data.settings?.trial_days??7)});clearStudioForm();await refresh('Estúdio salvo.')}catch(ex){toast(ex.message||'Falha ao salvar estúdio.')}};$('couponForm').onsubmit=async e=>{e.preventDefault();try{const row={code:$('cpCode').value.trim().toUpperCase(),discount_type:$('cpType').value,value:Number($('cpValue').value),max_redemptions:Number($('cpLimit').value||0)||null,expires_at:$('cpExpires').value?new Date(`${$('cpExpires').value}T23:59:59`).toISOString():null,active:true};const {error}=await IntornaCloud.client.from('coupons').insert(row);if(error)throw error;e.target.reset();await refresh('Cupom criado.')}catch(ex){toast(ex.message||'Falha ao criar cupom.')}};$('noticeForm').onsubmit=async e=>{e.preventDefault();try{const {error}=await IntornaCloud.client.from('announcements').insert({title:$('nTitle').value.trim(),body:$('nBody').value.trim(),audience:$('nAudience').value,active:true});if(error)throw error;e.target.reset();await refresh('Aviso publicado.')}catch(ex){toast(ex.message||'Falha ao publicar aviso.')}};$('settingsForm').onsubmit=async e=>{e.preventDefault();try{const updates={brand:$('cfgBrand').value.trim(),support_email:$('cfgEmail').value.trim()||null,support_whatsapp:$('cfgWhatsapp').value.trim()||null,pix:$('cfgPix').value.trim()||null,trial_days:Number($('cfgTrial').value||7),maintenance:$('cfgMaintenance').value==='true',maintenance_message:$('cfgMaintenanceMessage').value};const {error}=await IntornaCloud.client.from('platform_settings').update(updates).eq('id',1);if(error)throw error;await refresh('Configurações salvas.')}catch(ex){toast(ex.message||'Falha ao salvar configurações.')}}}
(async()=>{try{ctx=await IntornaCloud.requireAdmin();if(!ctx)return;$('today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});bind();await refresh()}catch(e){console.error(e);alert(e.message||'Falha ao abrir a administração.');location.href='/portal/'}})();
