import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.102.0";
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function sk(){const m=Deno.env.get('SUPABASE_SECRET_KEYS');if(m){try{const p=JSON.parse(m);if(p?.default)return p.default as string}catch(_){}}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''}
async function hash(v:string){const a=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function resolve(service:any,token:string){if(!token)throw new Error('Link inválido.');const h=await hash(token);const {data:l,error}=await service.from('portal_links').select('*').eq('token_hash',h).eq('enabled',true).maybeSingle();if(error||!l)throw new Error('Link inválido ou desativado.');if(l.expires_at&&new Date(l.expires_at)<new Date())throw new Error('Este link expirou.');const {data:o,error:oe}=await service.from('orders').select('*').eq('id',l.order_id).single();if(oe)throw oe;const [{data:c},{data:s},{data:p}]=await Promise.all([service.from('clients').select('id,name,whatsapp,email,city').eq('id',o.client_id).single(),service.from('studios').select('id,name,plan_id,settings,whatsapp').eq('id',l.studio_id).single(),service.from('plans').select('id,white_label').eq('id',o? (await service.from('studios').select('plan_id').eq('id',l.studio_id).single()).data?.plan_id:'free').single()]);return{link:l,order:o,client:c,studio:s,plan:p}}
async function signed(service:any,path:string|null){if(!path)return null;const {data}=await service.storage.from('intorna-media').createSignedUrl(path,3600);return data?.signedUrl||null}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Método não permitido'},405);try{const url=Deno.env.get('SUPABASE_URL')||'',secret=sk();if(!url||!secret)return json({error:'Backend indisponível'},503);const service=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const b=await req.json();const ctx=await resolve(service,String(b.token||''));const action=String(b.action||'get');
 if(action==='get'){const [{data:items},{data:sel},{data:refs},{data:pays}]=await Promise.all([service.from('gallery_items').select('*').eq('order_id',ctx.order.id).in('status',['preview','sold','released']).order('position'),service.from('gallery_selections').select('gallery_item_id,selected,client_note').eq('order_id',ctx.order.id),service.from('client_references').select('id,original_name,note,created_at').eq('order_id',ctx.order.id).order('created_at',{ascending:false}),service.from('client_payments').select('id,amount,status,billing_type,invoice_url,pix_payload,created_at').eq('order_id',ctx.order.id).order('created_at',{ascending:false}).limit(5)]);
  const out=[];for(const it of items||[]){const previewUrl=await signed(service,it.preview_path||it.final_path);let finalUrl=null;if(['sold','released'].includes(it.status)&&it.final_path)finalUrl=await signed(service,it.final_path);out.push({...it,preview_url:previewUrl,final_url:finalUrl,preview_path:undefined,final_path:undefined})}
  const wl=ctx.plan?.white_label===true;const branding=ctx.studio.settings?.white_label||{};let brandOut=wl?{...branding}:{};if(wl&&branding.logo_path)brandOut.logo_url=await signed(service,branding.logo_path);const op=ctx.studio.settings?.operational||{};const packs=[{id:'essencial',name:'Essencial',photos:3,price:19.90},{id:'premium',name:'Premium',photos:6,price:27.90},{id:'gold',name:'Gold',photos:10,price:35.00},{id:'platinum',name:'Platinum',photos:20,price:59.90}];const pi=packs.findIndex(x=>x.name.toLowerCase()===String(ctx.order.package_name||'').toLowerCase()||x.photos===Number(ctx.order.included_photos));const upgrade=pi>=0&&pi<packs.length-1?{target:packs[pi+1].id,name:packs[pi+1].name,photos:packs[pi+1].photos,amount:Number((packs[pi+1].price-packs[pi].price).toFixed(2))}:null;return json({ok:true,order:{id:ctx.order.id,package_name:ctx.order.package_name,included_photos:ctx.order.included_photos,status:ctx.order.status,deadline_at:ctx.order.deadline_at},client:ctx.client,studio:{name:ctx.studio.name,whatsapp:ctx.studio.whatsapp,white_label:wl,branding:brandOut,powered_by:!wl},pricing:{single:Number(op.extraPhotoPrice||4.90),bundle3:Number(op.bundle3Price||12.90),bundle5:Number(op.bundle5Price||19.90)},upgrade,gallery:out,selections:sel||[],references:refs||[],payments:pays||[]})}
 if(action==='select'){const itemId=String(b.itemId||'');const {data:item}=await service.from('gallery_items').select('id,studio_id,order_id').eq('id',itemId).eq('order_id',ctx.order.id).maybeSingle();if(!item)return json({error:'Foto inválida'},404);const {error}=await service.from('gallery_selections').upsert({studio_id:item.studio_id,order_id:item.order_id,gallery_item_id:item.id,selected:b.selected!==false,client_note:String(b.note||'')},{onConflict:'gallery_item_id'});if(error)throw error;return json({ok:true})}
 if(action==='reference_upload_url'){const filename=String(b.filename||'foto.jpg').replace(/[^a-zA-Z0-9._-]/g,'_');const ext=filename.split('.').pop()?.toLowerCase()||'jpg';if(!['jpg','jpeg','png','webp'].includes(ext))return json({error:'Formato não permitido'},400);const path=`${ctx.studio.id}/${ctx.order.id}/references/${crypto.randomUUID()}.${ext}`;const {data,error}=await service.storage.from('intorna-media').createSignedUploadUrl(path);if(error)throw error;return json({ok:true,path,token:data.token})}
 if(action==='reference_complete'){const path=String(b.path||'');if(!path.startsWith(`${ctx.studio.id}/${ctx.order.id}/references/`))return json({error:'Caminho inválido'},400);const {data,error}=await service.from('client_references').insert({studio_id:ctx.studio.id,order_id:ctx.order.id,file_path:path,original_name:String(b.originalName||'referência'),mime_type:String(b.mimeType||'image/jpeg'),note:String(b.note||''),source:'client'}).select('id,original_name,note,created_at').single();if(error)throw error;return json({ok:true,reference:data})}
 return json({error:'Ação desconhecida'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},400)}});
